[alembic]
# Path to migration scripts
script_location = %(here)s/alembic
# Database URL will be taken from the environment variable AUTORCA_DATABASE_URL at runtime.
sqlalchemy.url = postgresql+psycopg2://autorca:autorca_test@localhost:5433/autorca_test

timezone = utc

[log]
level = WARN

[formatter]
format = %(asctime)s %(levelname)s %(message)s
