"""Run AutoRCA against three incidents generated by real subprocesses/files.

This is intentionally a scenario runner, not a fixture provider:
the failing applications and Git history are created and executed at runtime.
Use --llm only when real provider credentials are configured.
"""

from __future__ import annotations

import argparse
import json
import os
import socket
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

from collectors.file_collector import FileCollector
from collectors.git_collector import GitCollector
from llm import LLMAnalysisService, OpenAICompatibleLLMClient
from pipeline import AnalysisPipeline, PipelineInput, PipelineResult
from rca_request.rca_request_builder import RCARequestBuilder, RepositoryContext
from reporting.incident_report_renderer import IncidentReportRenderer

PROJECT_ROOT = Path(__file__).resolve().parent
RULES_CONFIG = PROJECT_ROOT / "rules" / "rules.config.json"
TAXONOMY = PROJECT_ROOT / "taxonomy" / "taxonomy.yaml"


@dataclass(frozen=True)
class ScenarioArtifacts:
    name: str
    command: list[str]
    repository: Path
    source_name: str
    source_file: Path
    commit_sha: str
    branch: str
    environment: str


def _run(command: list[str], *, cwd: Path | None = None, env: dict | None = None) -> subprocess.CompletedProcess[str]:
    completed = subprocess.run(command, cwd=cwd, env=env, capture_output=True, text=True)
    if completed.returncode != 0:
        raise RuntimeError(
            f"Command failed ({completed.returncode}): {' '.join(command)}\n"
            f"stdout: {completed.stdout}\nstderr: {completed.stderr}"
        )
    return completed


def _git(repo: Path, *args: str) -> None:
    _run(["git", "-C", str(repo), *args])


def _init_repo(repo: Path) -> None:
    repo.mkdir()
    _git(repo, "init", "-q")
    _git(repo, "config", "user.email", "autorca-scenario@local")
    _git(repo, "config", "user.name", "AutoRCA Scenario")


def _run_real_app(script: Path, output_file: Path, *, env: dict | None = None) -> None:
    completed = subprocess.run(
        [sys.executable, str(script)],
        cwd=script.parent,
        env=env,
        capture_output=True,
        text=True,
    )
    output_file.write_text(
        (completed.stdout or "") + (completed.stderr or ""),
        encoding="utf-8",
    )
    if completed.returncode == 0:
        raise RuntimeError(f"Expected real failure, but command succeeded: {script}")


def _log_stage(scenario: str, stage: str, value: object) -> None:
    """Print inspectable execution proof without contaminating JSON stdout."""
    print(
        f"\n[{scenario}] {stage}\n"
        f"{json.dumps(value, ensure_ascii=False, indent=2, default=str)}",
        file=sys.stderr,
    )


def create_missing_env_scenario(root: Path) -> ScenarioArtifacts:
    repo = root / "missing-env-repo"
    _init_repo(repo)
    app = repo / "app.py"
    app.write_text("import os\nprint(os.environ['PORT'])\n", encoding="utf-8")
    env_file = repo / ".env"
    env_file.write_text("DEBUG=true\nPORT=8000\n", encoding="utf-8")
    _git(repo, "add", "app.py")
    _git(repo, "add", "-f", ".env")
    _git(repo, "commit", "-q", "-m", "Initial deployment configuration")
    env_file.write_text("DEBUG=true\n", encoding="utf-8")
    _git(repo, "add", "-f", ".env")
    _git(repo, "commit", "-q", "-m", "Remove required PORT variable")

    environment = os.environ.copy()
    environment.pop("PORT", None)
    traceback = root / "missing-env-traceback.txt"
    _run_real_app(app, traceback, env=environment)
    git = GitCollector(str(repo))
    return ScenarioArtifacts(
        name="Missing Environment Variable",
        command=[sys.executable, str(app)],
        repository=repo,
        source_name="traceback",
        source_file=traceback,
        commit_sha=git.resolve_commit_sha(),
        branch=git.resolve_branch(),
        environment="production",
    )


def create_missing_dependency_scenario(root: Path) -> ScenarioArtifacts:
    repo = root / "missing-dependency-repo"
    _init_repo(repo)
    app = repo / "app.py"
    app.write_text(
        "import autorca_dependency_that_is_really_unavailable_20260823\n",
        encoding="utf-8",
    )
    _git(repo, "add", "app.py")
    _git(repo, "commit", "-q", "-m", "Add application dependency")
    traceback = root / "missing-dependency-traceback.txt"
    _run_real_app(app, traceback)
    git = GitCollector(str(repo))
    return ScenarioArtifacts(
        name="Missing Dependency",
        command=[sys.executable, str(app)],
        repository=repo,
        source_name="traceback",
        source_file=traceback,
        commit_sha=git.resolve_commit_sha(),
        branch=git.resolve_branch(),
        environment="production",
    )


def create_port_conflict_scenario(root: Path) -> ScenarioArtifacts:
    repo = root / "port-conflict-repo"
    _init_repo(repo)
    app = repo / "bind.py"
    app.write_text(
        "import socket\n"
        "import sys\n"
        "sock = socket.socket()\n"
        "sock.bind(('127.0.0.1', int(sys.argv[1])))\n",
        encoding="utf-8",
    )
    _git(repo, "add", "bind.py")
    _git(repo, "commit", "-q", "-m", "Add application server")

    holder = socket.socket()
    holder.bind(("127.0.0.1", 0))
    port = holder.getsockname()[1]
    holder.listen(1)
    output = root / "port-conflict-output.txt"
    completed = subprocess.run(
        [sys.executable, str(app), str(port)],
        cwd=repo,
        capture_output=True,
        text=True,
    )
    holder.close()
    output.write_text(
        (completed.stdout or "") + (completed.stderr or ""),
        encoding="utf-8",
    )
    if completed.returncode == 0:
        raise RuntimeError("Expected the second real server process to fail.")
    git = GitCollector(str(repo))
    return ScenarioArtifacts(
        name="Port Conflict",
        command=[sys.executable, str(app), str(port)],
        repository=repo,
        source_name="docker_output",
        source_file=output,
        commit_sha=git.resolve_commit_sha(),
        branch=git.resolve_branch(),
        environment="production",
    )


def _build_pipeline() -> AnalysisPipeline:
    return AnalysisPipeline.from_config_files(RULES_CONFIG, TAXONOMY)


def analyze_artifacts(
    artifacts: ScenarioArtifacts,
    pipeline: AnalysisPipeline,
    *,
    use_llm: bool,
) -> dict:
    git = GitCollector(str(artifacts.repository))
    diff = git.collect_diff(commit=artifacts.commit_sha)
    source = FileCollector.collect(str(artifacts.source_file))
    _log_stage(
        artifacts.name,
        "REAL APPLICATION FAILURE",
        {
            "command": artifacts.command,
            "source_file": str(artifacts.source_file),
            "output": source.strip(),
        },
    )
    _log_stage(
        artifacts.name,
        "COLLECTORS",
        {
            "git_diff": {"collected": True, "characters": len(diff), "content": diff},
            artifacts.source_name: {
                "collected": True,
                "characters": len(source),
                "content": source,
            },
            "commit_sha": artifacts.commit_sha,
            "branch": artifacts.branch,
        },
    )
    analysis_number = {
        "Missing Environment Variable": "001",
        "Missing Dependency": "002",
        "Port Conflict": "003",
    }[artifacts.name]
    result: PipelineResult = pipeline.run(
        PipelineInput(
            analysis_id=f"AR20260823-{analysis_number}",
            sources={"git_diff": diff, artifacts.source_name: source},
        )
    )
    _log_stage(
        artifacts.name,
        "OBSERVATIONS",
        [observation.to_dict() for observation in result.observations],
    )
    _log_stage(artifacts.name, "EVIDENCE", result.evidence_list)
    _log_stage(
        artifacts.name,
        "HYPOTHESES",
        [hypothesis.to_dict() for hypothesis in result.hypotheses],
    )
    selected = result.selected
    evidence_types = [item["failure_type_id"] for item in result.evidence_list]
    if not selected:
        raise RuntimeError(f"{artifacts.name}: deterministic engine selected no root cause.")

    builder = RCARequestBuilder(
        rule_engine=pipeline._rule_engine,
        scoring_engine=pipeline._scoring_engine,
        taxonomy_index=pipeline._taxonomy_index,
        rules_config=pipeline._rules_config,
    )
    request = builder.build(
        analysis_id=result.analysis_id,
        selected=selected,
        all_hypotheses=result.hypotheses,
        evidence_list=result.evidence_list,
        repository_context=RepositoryContext(
            full_name=artifacts.repository.name,
            branch=artifacts.branch,
            commit_sha=artifacts.commit_sha,
            environment=artifacts.environment,
        ),
        diff_source=diff,
        log_source=source,
    )
    request_payload = request.to_dict()
    _log_stage(artifacts.name, "SELECTED HYPOTHESIS", selected.to_dict())
    _log_stage(artifacts.name, "RCA REQUEST", request_payload)
    deterministic_report = IncidentReportRenderer(
        fix_hints=pipeline._rules_config.fix_hints
    ).render(
        result,
        commit_sha=artifacts.commit_sha,
        confidence=pipeline.compute_confidence(selected.score),
    )
    output = {
        "scenario": artifacts.name,
        "command": artifacts.command,
        "trace_or_output_file": str(artifacts.source_file),
        "observed_error": source.strip(),
        "commit_sha": artifacts.commit_sha,
        "branch": artifacts.branch,
        "detected_failure_types": evidence_types,
        "selected_root_cause": selected.label if selected else None,
        "confidence": pipeline.compute_confidence(selected.score) if selected else None,
        "observations": [observation.to_dict() for observation in result.observations],
        "evidence": result.evidence_list,
        "hypotheses": [hypothesis.to_dict() for hypothesis in result.hypotheses],
        "rca_request": request_payload,
        "deterministic_incident_report": deterministic_report,
        "llm_status": "NOT VERIFIED",
        "final_rca": None,
        "validator_status": "NOT RUN",
    }

    if use_llm:
        output["final_rca"] = LLMAnalysisService(
            OpenAICompatibleLLMClient()
        ).generate_validated(request)
        output["llm_status"] = "VERIFIED"
        output["validator_status"] = "ACCEPTED"
        output["final_incident_report"] = output["final_rca"].get("incident_report")
        _log_stage(artifacts.name, "FINAL RCA", output["final_rca"])
        _log_stage(artifacts.name, "FINAL RCA VALIDATOR", {"status": "ACCEPTED"})
    else:
        _log_stage(
            artifacts.name,
            "FINAL RCA / VALIDATOR",
            {"status": "NOT RUN", "reason": "Use --llm with real provider configuration."},
        )
    return output


SCENARIO_BUILDERS: tuple[Callable[[Path], ScenarioArtifacts], ...] = (
    create_missing_env_scenario,
    create_missing_dependency_scenario,
    create_port_conflict_scenario,
)


def run_all(*, use_llm: bool = False) -> list[dict]:
    with tempfile.TemporaryDirectory(prefix="autorca-real-scenarios-") as directory:
        root = Path(directory)
        pipeline = _build_pipeline()
        return [
            analyze_artifacts(builder(root), pipeline, use_llm=use_llm)
            for builder in SCENARIO_BUILDERS
        ]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run AutoRCA on three real incidents.")
    parser.add_argument(
        "--llm",
        action="store_true",
        help="Use the configured real LLM and FinalRCAValidator; never falls back to fake output.",
    )
    args = parser.parse_args(argv)
    try:
        print(json.dumps(run_all(use_llm=args.llm), ensure_ascii=False, indent=2))
        return 0
    except Exception as exc:
        print(f"[error] {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())